import { SkillEffectType } from '@/models/shared/enums';

/**
 * スキル効果の説明
 */
export const SKILL_EFFECT_DESCRIPTIONS: Record<SkillEffectType, string> = {
  [SkillEffectType.HEART_CAPTURE]:
    'スキルハートを生成する。多くのものは、現在の1回あたりビートハート出現個数に比例して効果が増減する。',
  [SkillEffectType.WIDE_HEART]:
    '画面上に同時に存在できるハート数の上限を増加させる。',
  [SkillEffectType.LOVE_ATTRACT]:
    '獲得するLOVEを上昇する。効果期間は「ステージ中」「セクション中」「次のハート回収時」などのバリエーションがある。',
  [SkillEffectType.VOLTAGE_GAIN]:
    'ボルテージPt.を獲得する。',
  [SkillEffectType.HEART_BOOST]:
    'スキルハート獲得効果による獲得数を増加させる。',
  [SkillEffectType.WIDE_HEART_BOOST]:
    'ハート上限個数増加効果を増強する。',
  [SkillEffectType.ATTRACT_BOOST]:
    'ラブアトラクト効果を増強する。',
  [SkillEffectType.VOLTAGE_BOOST]:
    'ボルテージゲイン効果を増強する。',
  [SkillEffectType.VIBES]:
    'ビートハートの出現個数を増加させる。一部を除くハートキャプチャの効能も上がる。',
  [SkillEffectType.AMBIENCE]:
    'ハッピー、メロウいずれかの方向にムード値を増減する。',
  [SkillEffectType.MENTAL_RECOVER]:
    'メンタル最大値に対する一定割合のメンタルを回復する。',
  [SkillEffectType.MENTAL_PROTECT]:
    'メンタル最大値に対する一定割合のメンタル自然減少を無効化する。防げるのは自然減少のみで、スキルやセクション効果などによるメンタル減少は防げない。',
  [SkillEffectType.MENTAL_GUARD]:
    'メンタル最大値に対する一定割合のメンタル直接ダメージを無効化する。',
  [SkillEffectType.RESHUFFLE]:
    '手札を全て捨てた後、スキルを手札上限まで引く。',
  [SkillEffectType.EXTEND_HAND]:
    '手札の上限枚数を増加させる。',
  [SkillEffectType.IMITATION]:
    'スキル使用後にカードがステージ上にセットされ、何かを一定量吸収して別の何かに変換する。',
  [SkillEffectType.BLESSING]:
    '他のカードのスキルの消費APを減少させる。',
  [SkillEffectType.AP_GAIN]:
    'APを直接増加させる。ただし上限を超えることはない。',
  [SkillEffectType.HEAT_UP]:
    'AP回復速度を増加させる。',
  [SkillEffectType.BELIEF]:
    'メンタルが0以下になってもメンタルダウンしなくなる。',
  [SkillEffectType.IGNITION]:
    '姫芽を《イグニッションモード》にする。104期以降の楽曲でのみ効果がある。103期楽曲では何の効果も及ぼさない。',
  [SkillEffectType.SEARCH]:
    'カードドロー確率を大幅に上げる効果を検索する。',
};
