export enum Rarity {
  UR = 'UR',
  SR = 'SR',
  R = 'R',
  DR = 'DR',
  BR = 'BR',
  LR = 'LR',
}

export enum StyleType {
  CHEERLEADER = 'CHEERLEADER',
  TRICKSTER = 'TRICKSTER',
  PERFORMER = 'PERFORMER',
  MOODMAKER = 'MOODMAKER',
}

export enum LimitedType {
  PERMANENT = 'PERMANENT',
  LIMITED = 'LIMITED',
  SPRING_LIMITED = 'SPRING_LIMITED',
  SUMMER_LIMITED = 'SUMMER_LIMITED',
  AUTUMN_LIMITED = 'AUTUMN_LIMITED',
  WINTER_LIMITED = 'WINTER_LIMITED',
  BIRTHDAY_LIMITED = 'BIRTHDAY_LIMITED',
  LEG_LIMITED = 'LEG_LIMITED',
  BATTLE_LIMITED = 'BATTLE_LIMITED',
  PARTY_LIMITED = 'PARTY_LIMITED',
  ACTIVITY_LIMITED = 'ACTIVITY_LIMITED',
  GRADUATE_LIMITED = 'GRADUATE_LIMITED',
  LOGIN_BONUS = 'LOGIN_BONUS',
  REWARD = 'REWARD',
}

export enum ParentType {
  SPECIAL_APPEAL = 'SPECIAL_APPEAL',
  SKILL = 'SKILL',
  TRAIT = 'TRAIT',
}

export enum FavoriteMode {
  NONE = 'NONE',
  SMILE = 'SMILE',
  PURE = 'PURE',
  COOL = 'COOL',
}
