export enum Rarity {
  UR = 'UR',
  SR = 'SR',
  R = 'R',
  DR = 'DR',
  BR = 'BR',
  LR = 'LR',
}

export enum StyleType {
  CHEERLEADER = 'CHEERLEADER',
  TRICKSTER = 'TRICKSTER',
  PERFORMER = 'PERFORMER',
  MOODMAKER = 'MOODMAKER',
}

export enum LimitedType {
  PERMANENT = 'PERMANENT',
  LIMITED = 'LIMITED',
  SPRING_LIMITED = 'SPRING_LIMITED',
  SUMMER_LIMITED = 'SUMMER_LIMITED',
  AUTUMN_LIMITED = 'AUTUMN_LIMITED',
  WINTER_LIMITED = 'WINTER_LIMITED',
  BIRTHDAY_LIMITED = 'BIRTHDAY_LIMITED',
  LEG_LIMITED = 'LEG_LIMITED',
  BATTLE_LIMITED = 'BATTLE_LIMITED',
  BANGDREAM_LIMITED = 'BANGDREAM_LIMITED',
  PARTY_LIMITED = 'PARTY_LIMITED',
  ACTIVITY_LIMITED = 'ACTIVITY_LIMITED',
  GRADUATE_LIMITED = 'GRADUATE_LIMITED',
  LOGIN_BONUS = 'LOGIN_BONUS',
  REWARD = 'REWARD',
}

export enum ParentType {
  SPECIAL_APPEAL = 'SPECIAL_APPEAL',
  SKILL = 'SKILL',
  TRAIT = 'TRAIT',
}

export enum FavoriteMode {
  NONE = 'NONE',
  HAPPY = 'HAPPY',
  MELLOW = 'MELLOW',
  NEUTRAL = 'NEUTRAL',
}

export enum DeckType {
  TERM_103 = '103期',
  TERM_104 = '104期',
  TERM_105 = '105期',
  TERM_105_FT_KOZUE = '105期ft.梢',
  TERM_105_FT_TSUZURI = '105期ft.綴理',
  TERM_105_FT_MEGUMI = '105期ft.慈',
}

export enum SongAttribute {
  SMILE = 'スマイル',
  PURE = 'ピュア',
  COOL = 'クール',
}

export enum UserRole {
  ANONYMOUS = 'anonymous',
  EMAIL = 'email',
}

/**
 * スキル効果の種類
 */
export enum SkillEffectType {
  HEART_CAPTURE = 'HEART_CAPTURE',
  WIDE_HEART = 'WIDE_HEART',
  LOVE_ATTRACT = 'LOVE_ATTRACT',
  VOLTAGE_GAIN = 'VOLTAGE_GAIN',
  HEART_BOOST = 'HEART_BOOST',
  WIDE_HEART_BOOST = 'WIDE_HEART_BOOST',
  ATTRACT_BOOST = 'ATTRACT_BOOST',
  VOLTAGE_BOOST = 'VOLTAGE_BOOST',
  VIBES = 'VIBES',
  AMBIENCE = 'AMBIENCE',
  MENTAL_RECOVER = 'MENTAL_RECOVER',
  MENTAL_PROTECT = 'MENTAL_PROTECT',
  MENTAL_GUARD = 'MENTAL_GUARD',
  RESHUFFLE = 'RESHUFFLE',
  EXTEND_HAND = 'EXTEND_HAND',
  IMITATION = 'IMITATION',
  BLESSING = 'BLESSING',
  AP_GAIN = 'AP_GAIN',
  HEAT_UP = 'HEAT_UP',
  BELIEF = 'BELIEF',
  IGNITION = 'IGNITION',
}

/**
 * 特性効果の種類
 */
export enum TraitEffectType {
  HEART_COLLECT = 'HEART_COLLECT',
  INSTANCE = 'INSTANCE',
  ENCORE = 'ENCORE',
  SHOT = 'SHOT',
  DRAW = 'DRAW',
  AP_REDUCE = 'AP_REDUCE',
  AP_SUPPORT = 'AP_SUPPORT',
  INTERPRETATION = 'INTERPRETATION',
  ACCUMULATE = 'ACCUMULATE',
  OVER_SECTION = 'OVER_SECTION',
  SEARCH = 'SEARCH',
  CHAIN = 'CHAIN',
  FAVORITE = 'FAVORITE',
  REINFORCE = 'REINFORCE',
  UN_DRAW = 'UN_DRAW',
}

/**
 * スキル検索対象の種類
 */
export enum SkillSearchTarget {
  SPECIAL_APPEAL = 'SPECIAL_APPEAL',
  SKILL = 'SKILL',
  TRAIT = 'TRAIT',
}
