export enum Rarity {
  UR = 'UR',
  SR = 'SR',
  R = 'R',
  DR = 'DR',
  BR = 'BR',
  LR = 'LR',
}

export enum StyleType {
  CHEERLEADER = 'CHEERLEADER',
  TRICKSTER = 'TRICKSTER',
  PERFORMER = 'PERFORMER',
  MOODMAKER = 'MOODMAKER',
}

export enum LimitedType {
  PERMANENT = 'PERMANENT',
  LIMITED = 'LIMITED',
  SPRING_LIMITED = 'SPRING_LIMITED',
  SUMMER_LIMITED = 'SUMMER_LIMITED',
  AUTUMN_LIMITED = 'AUTUMN_LIMITED',
  WINTER_LIMITED = 'WINTER_LIMITED',
  BIRTHDAY_LIMITED = 'BIRTHDAY_LIMITED',
  LEG_LIMITED = 'LEG_LIMITED',
  BATTLE_LIMITED = 'BATTLE_LIMITED',
  PARTY_LIMITED = 'PARTY_LIMITED',
  ACTIVITY_LIMITED = 'ACTIVITY_LIMITED',
  GRADUATE_LIMITED = 'GRADUATE_LIMITED',
  LOGIN_BONUS = 'LOGIN_BONUS',
  REWARD = 'REWARD',
}

export enum ParentType {
  SPECIAL_APPEAL = 'SPECIAL_APPEAL',
  SKILL = 'SKILL',
  TRAIT = 'TRAIT',
}

export enum FavoriteMode {
  NONE = 'NONE',
  HAPPY = 'HAPPY',
  MELLOW = 'MELLOW',
  NEUTRAL = 'NEUTRAL',
}

export enum DeckType {
  TERM_103 = '103期',
  TERM_104 = '104期',
  TERM_105 = '105期',
  TERM_105_FT_KOZUE = '105期ft.梢',
  TERM_105_FT_TSUZURI = '105期ft.綴理',
  TERM_105_FT_MEGUMI = '105期ft.慈',
}

export enum SongAttribute {
  SMILE = 'スマイル',
  PURE = 'ピュア',
  COOL = 'クール',
}
